#Comment
name: CCUD test

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: gradle help
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: help
          build-root-directory: gradle-project

      - uses: actions/upload-artifact@v2
        with:
          name: build-scan-data
          path: ~/.gradle/build-scan-data

      - name: gradle assemble
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: assemble
          build-root-directory: gradle-project

      - uses: actions/upload-artifact@v2
        with:
          name: build-scan-data
          path: ~/.gradle/build-scan-data

  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - uses: actions/download-artifact@v2
        with:
          path: ~/.gradle

      - name: gradle publish scan
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: buildScanPublishPrevious
          build-root-directory: gradle-project
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{secrets.GRADLE_ENTERPRISE_ACCESS_KEY}}

      - name: gradle publish another scan
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: buildScanPublishPrevious
          build-root-directory: gradle-project
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{secrets.GRADLE_ENTERPRISE_ACCESS_KEY}}
